import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const INGREDIENTS = [
  // Fruits & Légumes
  { nom: 'Carotte', categorie: 'fruits-legumes' },
  { nom: 'Pomme de terre', categorie: 'fruits-legumes' },
  { nom: 'Oignon', categorie: 'fruits-legumes' },
  { nom: 'Ail', categorie: 'fruits-legumes' },
  { nom: 'Échalote', categorie: 'fruits-legumes' },
  { nom: 'Courgette', categorie: 'fruits-legumes' },
  { nom: 'Tomate', categorie: 'fruits-legumes' },
  { nom: 'Poivron rouge', categorie: 'fruits-legumes' },
  { nom: 'Poivron vert', categorie: 'fruits-legumes' },
  { nom: 'Poivron jaune', categorie: 'fruits-legumes' },
  { nom: 'Aubergine', categorie: 'fruits-legumes' },
  { nom: 'Concombre', categorie: 'fruits-legumes' },
  { nom: 'Laitue', categorie: 'fruits-legumes' },
  { nom: 'Épinard', categorie: 'fruits-legumes' },
  { nom: 'Avocat', categorie: 'fruits-legumes' },
  { nom: 'Citron', categorie: 'fruits-legumes' },
  { nom: 'Citron vert', categorie: 'fruits-legumes' },
  { nom: 'Banane', categorie: 'fruits-legumes' },
  { nom: 'Pomme', categorie: 'fruits-legumes' },
  { nom: 'Poire', categorie: 'fruits-legumes' },
  { nom: 'Fraise', categorie: 'fruits-legumes' },
  { nom: 'Framboise', categorie: 'fruits-legumes' },
  { nom: 'Orange', categorie: 'fruits-legumes' },
  { nom: 'Mandarine', categorie: 'fruits-legumes' },
  { nom: 'Pamplemousse', categorie: 'fruits-legumes' },
  { nom: 'Champignon de Paris', categorie: 'fruits-legumes' },
  { nom: 'Poireau', categorie: 'fruits-legumes' },
  { nom: 'Brocoli', categorie: 'fruits-legumes' },
  { nom: 'Chou-fleur', categorie: 'fruits-legumes' },
  { nom: 'Haricot vert', categorie: 'fruits-legumes' },
  { nom: 'Asperge', categorie: 'fruits-legumes' },
  { nom: 'Céleri-branche', categorie: 'fruits-legumes' },
  { nom: 'Céleri-rave', categorie: 'fruits-legumes' },
  { nom: 'Navet', categorie: 'fruits-legumes' },
  { nom: 'Radis', categorie: 'fruits-legumes' },
  { nom: 'Patate douce', categorie: 'fruits-legumes' },
  { nom: 'Courge Butternut', categorie: 'fruits-legumes' },
  { nom: 'Potimarron', categorie: 'fruits-legumes' },
  { nom: 'Pêche', categorie: 'fruits-legumes' },
  { nom: 'Abricot', categorie: 'fruits-legumes' },
  { nom: 'Cerise', categorie: 'fruits-legumes' },
  { nom: 'Melon', categorie: 'fruits-legumes' },
  { nom: 'Pastèque', categorie: 'fruits-legumes' },
  { nom: 'Prune', categorie: 'fruits-legumes' },
  { nom: 'Raisin', categorie: 'fruits-legumes' },
  { nom: 'Kiwi', categorie: 'fruits-legumes' },
  { nom: 'Mangue', categorie: 'fruits-legumes' },
  { nom: 'Ananas', categorie: 'fruits-legumes' },
  { nom: 'Clémentine', categorie: 'fruits-legumes' },
  { nom: 'Grenade', categorie: 'fruits-legumes' },
  { nom: 'Figue', categorie: 'fruits-legumes' },
  { nom: 'Datte', categorie: 'fruits-legumes' },
  { nom: 'Chou vert', categorie: 'fruits-legumes' },
  { nom: 'Chou rouge', categorie: 'fruits-legumes' },
  { nom: 'Chou de Bruxelles', categorie: 'fruits-legumes' },
  { nom: 'Artichaut', categorie: 'fruits-legumes' },
  { nom: 'Petit pois', categorie: 'fruits-legumes' },
  { nom: 'Fenouil', categorie: 'fruits-legumes' },
  { nom: 'Cresson', categorie: 'fruits-legumes' },
  { nom: 'Mâche', categorie: 'fruits-legumes' },
  { nom: 'Roquette', categorie: 'fruits-legumes' },
  { nom: 'Endive', categorie: 'fruits-legumes' },
  { nom: 'Blette', categorie: 'fruits-legumes' },
  { nom: 'Gingembre', categorie: 'fruits-legumes' },
  { nom: 'Curcuma frais', categorie: 'fruits-legumes' },
  { nom: 'Myrtille', categorie: 'fruits-legumes' },
  { nom: 'Mûre', categorie: 'fruits-legumes' },
  { nom: 'Cassis', categorie: 'fruits-legumes' },
  { nom: 'Groseille', categorie: 'fruits-legumes' },
  { nom: 'Pruneau', categorie: 'fruits-legumes' },
  { nom: 'Kaki', categorie: 'fruits-legumes' },
  { nom: 'Litchi', categorie: 'fruits-legumes' },
  { nom: 'Marron', categorie: 'fruits-legumes' },
  { nom: 'Châtaigne', categorie: 'fruits-legumes' },
  { nom: 'Pâtisson', categorie: 'fruits-legumes' },
  { nom: 'Courge spaghetti', categorie: 'fruits-legumes' },
  { nom: 'Pissenlit', categorie: 'fruits-legumes' },
  { nom: 'Rhubarbe', categorie: 'fruits-legumes' },
  { nom: 'Topinambour', categorie: 'fruits-legumes' },
  { nom: 'Rutabaga', categorie: 'fruits-legumes' },

  // Boucherie & Poissonnerie
  { nom: 'Escalope de poulet', categorie: 'boucherie-poissonnerie' },
  { nom: 'Filet de poulet', categorie: 'boucherie-poissonnerie' },
  { nom: 'Steak haché', categorie: 'boucherie-poissonnerie' },
  { nom: 'Côte de bœuf', categorie: 'boucherie-poissonnerie' },
  { nom: 'Rôti de porc', categorie: 'boucherie-poissonnerie' },
  { nom: 'Côte de porc', categorie: 'boucherie-poissonnerie' },
  { nom: 'Échine de porc', categorie: 'boucherie-poissonnerie' },
  { nom: 'Gigot d\'agneau', categorie: 'boucherie-poissonnerie' },
  { nom: 'Filet mignon', categorie: 'boucherie-poissonnerie' },
  { nom: 'Jambon cru', categorie: 'boucherie-poissonnerie' },
  { nom: 'Lardons nature', categorie: 'boucherie-poissonnerie' },
  { nom: 'Lardons fumés', categorie: 'boucherie-poissonnerie' },
  { nom: 'Pavé de saumon', categorie: 'boucherie-poissonnerie' },
  { nom: 'Filet de cabillaud', categorie: 'boucherie-poissonnerie' },
  { nom: 'Truite', categorie: 'boucherie-poissonnerie' },
  { nom: 'Crevettes', categorie: 'boucherie-poissonnerie' },
  { nom: 'Colin', categorie: 'boucherie-poissonnerie' },
  { nom: 'Thon frais', categorie: 'boucherie-poissonnerie' },
  { nom: 'Moules', categorie: 'boucherie-poissonnerie' },
  { nom: 'Merlan', categorie: 'boucherie-poissonnerie' },
  { nom: 'Bar', categorie: 'boucherie-poissonnerie' },
  { nom: 'Dorade', categorie: 'boucherie-poissonnerie' },
  { nom: 'Steak de canard', categorie: 'boucherie-poissonnerie' },
  { nom: 'Cuisse de canard', categorie: 'boucherie-poissonnerie' },
  { nom: 'Magret de canard', categorie: 'boucherie-poissonnerie' },
  { nom: 'Escalope de dinde', categorie: 'boucherie-poissonnerie' },
  { nom: 'Haché de porc', categorie: 'boucherie-poissonnerie' },
  { nom: 'Haché de bœuf', categorie: 'boucherie-poissonnerie' },
  { nom: 'Épaule d\'agneau', categorie: 'boucherie-poissonnerie' },
  { nom: 'Côte d\'agneau', categorie: 'boucherie-poissonnerie' },
  { nom: 'Saucisse de Strasbourg', categorie: 'boucherie-poissonnerie' },
  { nom: 'Saucisse de Montbéliard', categorie: 'boucherie-poissonnerie' },
  { nom: 'Saucisse de Morteau', categorie: 'boucherie-poissonnerie' },
  { nom: 'Merguez', categorie: 'boucherie-poissonnerie' },
  { nom: 'Chipotle', categorie: 'boucherie-poissonnerie' },
  { nom: 'Travers de porc (Ribs)', categorie: 'boucherie-poissonnerie' },
  { nom: 'Coquelet', categorie: 'boucherie-poissonnerie' },
  { nom: 'Pintade', categorie: 'boucherie-poissonnerie' },
  { nom: 'Lapin', categorie: 'boucherie-poissonnerie' },
  { nom: 'Filet de sole', categorie: 'boucherie-poissonnerie' },
  { nom: 'Filet de merlu', categorie: 'boucherie-poissonnerie' },
  { nom: 'Sardines fraîches', categorie: 'boucherie-poissonnerie' },
  { nom: 'Maquereau', categorie: 'boucherie-poissonnerie' },
  { nom: 'Noix de Saint-Jacques', categorie: 'boucherie-poissonnerie' },
  { nom: 'Calamar', categorie: 'boucherie-poissonnerie' },
  { nom: 'Poulpe', categorie: 'boucherie-poissonnerie' },
  { nom: 'Huîtres', categorie: 'boucherie-poissonnerie' },
  { nom: 'Tourteau', categorie: 'boucherie-poissonnerie' },
  { nom: 'Homard', categorie: 'boucherie-poissonnerie' },
  { nom: 'Langoustines', categorie: 'boucherie-poissonnerie' },

  // Charcuterie (Boucherie & Poissonnerie)
  { nom: 'Jambon blanc', categorie: 'boucherie-poissonnerie' },
  { nom: 'Saucisson', categorie: 'boucherie-poissonnerie' },
  { nom: 'Jambon de Bayonne', categorie: 'boucherie-poissonnerie' },
  { nom: 'Bacon', categorie: 'boucherie-poissonnerie' },
  { nom: 'Pâté de campagne', categorie: 'boucherie-poissonnerie' },
  { nom: 'Rillettes de porc', categorie: 'boucherie-poissonnerie' },
  { nom: 'Rillettes de saumon', categorie: 'boucherie-poissonnerie' },
  { nom: 'Boudin noir', categorie: 'boucherie-poissonnerie' },
  { nom: 'Boudin blanc', categorie: 'boucherie-poissonnerie' },
  { nom: 'Saucisse de Toulouse', categorie: 'boucherie-poissonnerie' },
  { nom: 'Knacki', categorie: 'boucherie-poissonnerie' },
  { nom: 'Chorizo', categorie: 'boucherie-poissonnerie' },
  { nom: 'Mortadelle', categorie: 'boucherie-poissonnerie' },
  { nom: 'Pancetta', categorie: 'boucherie-poissonnerie' },
  { nom: 'Coppa', categorie: 'boucherie-poissonnerie' },
  { nom: 'Viande des Grisons', categorie: 'boucherie-poissonnerie' },
  { nom: 'Terrine', categorie: 'boucherie-poissonnerie' },
  { nom: 'Pâté en croûte', categorie: 'boucherie-poissonnerie' },

  // Rayon Frais
  { nom: 'Pâte feuilletée', categorie: 'frais' },
  { nom: 'Pâte brisée', categorie: 'frais' },
  { nom: 'Pâte sablée', categorie: 'frais' },
  { nom: 'Gnocchis', categorie: 'frais' },
  { nom: 'Tofu nature', categorie: 'frais' },
  { nom: 'Tofu fumé', categorie: 'frais' },
  { nom: 'Quiche Lorraine', categorie: 'frais' },
  { nom: 'Pizza fraîche', categorie: 'frais' },
  { nom: 'Lasagnes fraîches', categorie: 'frais' },
  { nom: 'Taboulé', categorie: 'frais' },
  { nom: 'Carottes râpées', categorie: 'frais' },
  { nom: 'Céleri rémoulade', categorie: 'frais' },
  { nom: 'Salade de pâtes', categorie: 'frais' },
  { nom: 'Rouleau de printemps', categorie: 'frais' },
  { nom: 'Nems', categorie: 'frais' },
  { nom: 'Galette de sarrasin', categorie: 'frais' },
  { nom: 'Crêpe salée', categorie: 'frais' },

  // Produits Laitiers & Œufs
  { nom: 'Lait demi-écrémé', categorie: 'produits-laitiers' },
  { nom: 'Lait entier', categorie: 'produits-laitiers' },
  { nom: 'Lait de chèvre', categorie: 'produits-laitiers' },
  { nom: 'Crème fraîche liquide', categorie: 'produits-laitiers' },
  { nom: 'Crème fraîche épaisse', categorie: 'produits-laitiers' },
  { nom: 'Crème liquide 30%', categorie: 'produits-laitiers' },
  { nom: 'Beurre doux', categorie: 'produits-laitiers' },
  { nom: 'Beurre demi-sel', categorie: 'produits-laitiers' },
  { nom: 'Œuf', categorie: 'produits-laitiers' },
  { nom: 'Yaourt nature', categorie: 'produits-laitiers' },
  { nom: 'Yaourt brassé', categorie: 'produits-laitiers' },
  { nom: 'Fromage blanc', categorie: 'produits-laitiers' },
  { nom: 'Mozzarella', categorie: 'produits-laitiers' },
  { nom: 'Parmesan', categorie: 'produits-laitiers' },
  { nom: 'Gruyère râpé', categorie: 'produits-laitiers' },
  { nom: 'Emmental râpé', categorie: 'produits-laitiers' },
  { nom: 'Camembert', categorie: 'produits-laitiers' },
  { nom: 'Brie', categorie: 'produits-laitiers' },
  { nom: 'Chèvre frais', categorie: 'produits-laitiers' },
  { nom: 'Bûche de chèvre', categorie: 'produits-laitiers' },
  { nom: 'Roquefort', categorie: 'produits-laitiers' },
  { nom: 'Mascarpone', categorie: 'produits-laitiers' },
  { nom: 'Feta', categorie: 'produits-laitiers' },
  { nom: 'Ricotta', categorie: 'produits-laitiers' },
  { nom: 'Fromage frais', categorie: 'produits-laitiers' },
  { nom: 'Kiri', categorie: 'produits-laitiers' },
  { nom: 'Cantal', categorie: 'produits-laitiers' },
  { nom: 'Comté', categorie: 'produits-laitiers' },
  { nom: 'Reblochon', categorie: 'produits-laitiers' },
  { nom: 'Beaufort', categorie: 'produits-laitiers' },
  { nom: 'Munster', categorie: 'produits-laitiers' },
  { nom: 'Tomme de Savoie', categorie: 'produits-laitiers' },
  { nom: 'Saint-Nectaire', categorie: 'produits-laitiers' },
  { nom: 'Gorgonzola', categorie: 'produits-laitiers' },
  { nom: 'Cheddar', categorie: 'produits-laitiers' },
  { nom: 'Gouda', categorie: 'produits-laitiers' },
  { nom: 'Mimolette', categorie: 'produits-laitiers' },
  { nom: 'Fromage à raclette', categorie: 'produits-laitiers' },
  { nom: 'Fondue savoyarde (mélange)', categorie: 'produits-laitiers' },
  { nom: 'Crème anglaise', categorie: 'produits-laitiers' },
  { nom: 'Yaourt grec', categorie: 'produits-laitiers' },
  { nom: 'Faisselle', categorie: 'produits-laitiers' },
  { nom: 'Lait de soja', categorie: 'produits-laitiers' },
  { nom: 'Lait d\'amande', categorie: 'produits-laitiers' },
  { nom: 'Lait d\'avoine', categorie: 'produits-laitiers' },
  { nom: 'Crème d\'Isigny', categorie: 'produits-laitiers' },

  // Boulangerie & Pâtisserie
  { nom: 'Baguette', categorie: 'boulangerie-patisserie' },
  { nom: 'Pain de mie', categorie: 'boulangerie-patisserie' },
  { nom: 'Pain complet', categorie: 'boulangerie-patisserie' },
  { nom: 'Pain aux céréales', categorie: 'boulangerie-patisserie' },
  { nom: 'Croissant', categorie: 'boulangerie-patisserie' },
  { nom: 'Pain au chocolat', categorie: 'boulangerie-patisserie' },
  { nom: 'Brioche', categorie: 'boulangerie-patisserie' },
  { nom: 'Pain à burger', categorie: 'boulangerie-patisserie' },
  { nom: 'Biscottes', categorie: 'boulangerie-patisserie' },
  { nom: 'Tortillas', categorie: 'boulangerie-patisserie' },
  { nom: 'Pain pita', categorie: 'boulangerie-patisserie' },
  { nom: 'Pain de seigle', categorie: 'boulangerie-patisserie' },
  { nom: 'Pain au levain', categorie: 'boulangerie-patisserie' },
  { nom: 'Chouquette', categorie: 'boulangerie-patisserie' },
  { nom: 'Pain aux raisins', categorie: 'boulangerie-patisserie' },
  { nom: 'Chaussons aux pommes', categorie: 'boulangerie-patisserie' },
  { nom: 'Madeleine', categorie: 'boulangerie-patisserie' },
  { nom: 'Pain d\'épices', categorie: 'boulangerie-patisserie' },
  { nom: 'Muffins', categorie: 'boulangerie-patisserie' },
  { nom: 'Cookies', categorie: 'boulangerie-patisserie' },
  { nom: 'Tartelette', categorie: 'boulangerie-patisserie' },
  { nom: 'Macarons', categorie: 'boulangerie-patisserie' },
  { nom: 'Pain suédois', categorie: 'boulangerie-patisserie' },
  { nom: 'Naan', categorie: 'boulangerie-patisserie' },
  { nom: 'Blinis', categorie: 'boulangerie-patisserie' },

  // Épicerie Salée
  { nom: 'Sel', categorie: 'epicerie-salee' },
  { nom: 'Poivre noir', categorie: 'epicerie-salee' },
  { nom: 'Huile d\'olive', categorie: 'epicerie-salee' },
  { nom: 'Huile de tournesol', categorie: 'epicerie-salee' },
  { nom: 'Huile de colza', categorie: 'epicerie-salee' },
  { nom: 'Huile de sésame', categorie: 'epicerie-salee' },
  { nom: 'Vinaigre de vin', categorie: 'epicerie-salee' },
  { nom: 'Vinaigre balsamique', categorie: 'epicerie-salee' },
  { nom: 'Vinaigre de cidre', categorie: 'epicerie-salee' },
  { nom: 'Moutarde de Dijon', categorie: 'epicerie-salee' },
  { nom: 'Moutarde à l\'ancienne', categorie: 'epicerie-salee' },
  { nom: 'Mayonnaise', categorie: 'epicerie-salee' },
  { nom: 'Ketchup', categorie: 'epicerie-salee' },
  { nom: 'Concentré de tomates', categorie: 'epicerie-salee' },
  { nom: 'Coulis de tomates', categorie: 'epicerie-salee' },
  { nom: 'Sauce tomate basilic', categorie: 'epicerie-salee' },
  { nom: 'Sauce pesto verde', categorie: 'epicerie-salee' },
  { nom: 'Sauce pesto rosso', categorie: 'epicerie-salee' },
  { nom: 'Spaghetti', categorie: 'epicerie-salee' },
  { nom: 'Penne', categorie: 'epicerie-salee' },
  { nom: 'Coquillettes', categorie: 'epicerie-salee' },
  { nom: 'Tagliatelles', categorie: 'epicerie-salee' },
  { nom: 'Lasagnes (plaques)', categorie: 'epicerie-salee' },
  { nom: 'Macaronis', categorie: 'epicerie-salee' },
  { nom: 'Riz basmati', categorie: 'epicerie-salee' },
  { nom: 'Riz blanc', categorie: 'epicerie-salee' },
  { nom: 'Riz thaï', categorie: 'epicerie-salee' },
  { nom: 'Riz arborio (risotto)', categorie: 'epicerie-salee' },
  { nom: 'Semoule de blé', categorie: 'epicerie-salee' },
  { nom: 'Lentilles vertes', categorie: 'epicerie-salee' },
  { nom: 'Lentilles corail', categorie: 'epicerie-salee' },
  { nom: 'Pois chiches', categorie: 'epicerie-salee' },
  { nom: 'Haricots rouges', categorie: 'epicerie-salee' },
  { nom: 'Haricots blancs', categorie: 'epicerie-salee' },
  { nom: 'Bouillon de légumes', categorie: 'epicerie-salee' },
  { nom: 'Bouillon de volaille', categorie: 'epicerie-salee' },
  { nom: 'Bouillon de bœuf', categorie: 'epicerie-salee' },
  { nom: 'Sauce soja salée', categorie: 'epicerie-salee' },
  { nom: 'Sauce soja sucrée', categorie: 'epicerie-salee' },
  { nom: 'Sauce teriyaki', categorie: 'epicerie-salee' },
  { nom: 'Sauce nuoc-mam', categorie: 'epicerie-salee' },
  { nom: 'Lait de coco', categorie: 'epicerie-salee' },
  { nom: 'Farine de blé T55', categorie: 'epicerie-salee' },
  { nom: 'Farine complète', categorie: 'epicerie-salee' },
  { nom: 'Fécule de maïs (Maïzena)', categorie: 'epicerie-salee' },
  { nom: 'Levure chimique', categorie: 'epicerie-salee' },
  { nom: 'Thon en boîte', categorie: 'epicerie-salee' },
  { nom: 'Sardines en boîte', categorie: 'epicerie-salee' },
  { nom: 'Maquereaux en boîte', categorie: 'epicerie-salee' },
  { nom: 'Tomates pelées en boîte', categorie: 'epicerie-salee' },
  { nom: 'Maïs en boîte', categorie: 'epicerie-salee' },
  { nom: 'Olives noires', categorie: 'epicerie-salee' },
  { nom: 'Olives vertes', categorie: 'epicerie-salee' },
  { nom: 'Pignons de pin', categorie: 'epicerie-salee' },
  { nom: 'Noix de cajou', categorie: 'epicerie-salee' },
  { nom: 'Graines de sésame', categorie: 'epicerie-salee' },
  { nom: 'Graines de courge', categorie: 'epicerie-salee' },
  { nom: 'Graines de chia', categorie: 'epicerie-salee' },
  { nom: 'Herbes de Provence', categorie: 'epicerie-salee' },
  { nom: 'Curry', categorie: 'epicerie-salee' },
  { nom: 'Paprika doux', categorie: 'epicerie-salee' },
  { nom: 'Paprika fumé', categorie: 'epicerie-salee' },
  { nom: 'Piment de Cayenne', categorie: 'epicerie-salee' },
  { nom: 'Cumin', categorie: 'epicerie-salee' },
  { nom: 'Origan', categorie: 'epicerie-salee' },
  { nom: 'Basilic séché', categorie: 'epicerie-salee' },
  { nom: 'Thym séché', categorie: 'epicerie-salee' },
  { nom: 'Romarin', categorie: 'epicerie-salee' },
  { nom: 'Cannelle (poudre)', categorie: 'epicerie-salee' },
  { nom: 'Muscade (noix ou poudre)', categorie: 'epicerie-salee' },
  { nom: 'Gingembre en poudre', categorie: 'epicerie-salee' },
  { nom: 'Purée de piments', categorie: 'epicerie-salee' },
  { nom: 'Sauce Worcester', categorie: 'epicerie-salee' },
  { nom: 'Cornichons', categorie: 'epicerie-salee' },
  { nom: 'Câpres', categorie: 'epicerie-salee' },
  { nom: 'Lait de coco en boîte', categorie: 'epicerie-salee' },
  { nom: 'Pois cassés', categorie: 'epicerie-salee' },
  { nom: 'Quinoa', categorie: 'epicerie-salee' },
  { nom: 'Boulgour', categorie: 'epicerie-salee' },
  { nom: 'Polenta', categorie: 'epicerie-salee' },
  { nom: 'Flocons d\'avoine', categorie: 'epicerie-salee' },

  // Épicerie Sucrée
  { nom: 'Sucre en poudre', categorie: 'epicerie-sucree' },
  { nom: 'Sucre roux (Cassonade)', categorie: 'epicerie-sucree' },
  { nom: 'Sucre vanillé', categorie: 'epicerie-sucree' },
  { nom: 'Miel', categorie: 'epicerie-sucree' },
  { nom: 'Chocolat noir pâtissier', categorie: 'epicerie-sucree' },
  { nom: 'Chocolat au lait', categorie: 'epicerie-sucree' },
  { nom: 'Pépites de chocolat', categorie: 'epicerie-sucree' },
  { nom: 'Confiture de fraises', categorie: 'epicerie-sucree' },
  { nom: 'Confiture d\'abricots', categorie: 'epicerie-sucree' },
  { nom: 'Confiture de framboises', categorie: 'epicerie-sucree' },
  { nom: 'Pâte à tartiner', categorie: 'epicerie-sucree' },
  { nom: 'Compote de pommes', categorie: 'epicerie-sucree' },
  { nom: 'Compote pommes-fraises', categorie: 'epicerie-sucree' },
  { nom: 'Sirop d\'érable', categorie: 'epicerie-sucree' },
  { nom: 'Amandes en poudre', categorie: 'epicerie-sucree' },
  { nom: 'Levure boulangère sèche', categorie: 'epicerie-sucree' },
  { nom: 'Levure de boulanger fraîche', categorie: 'epicerie-sucree' },
  { nom: 'Sucre glace', categorie: 'epicerie-sucree' },
  { nom: 'Noix de coco râpée', categorie: 'epicerie-sucree' },
  { nom: 'Extrait de vanille', categorie: 'epicerie-sucree' },
  { nom: 'Cacao en poudre non sucré', categorie: 'epicerie-sucree' },
  { nom: 'Caramel au beurre salé', categorie: 'epicerie-sucree' },
  { nom: 'Pralin', categorie: 'epicerie-sucree' },
  { nom: 'Raisins secs', categorie: 'epicerie-sucree' },
  { nom: 'Cerneaux de noix', categorie: 'epicerie-sucree' },
  { nom: 'Noisettes entières', categorie: 'epicerie-sucree' },
  { nom: 'Amandes effilées', categorie: 'epicerie-sucree' },
  { nom: 'Biscuits cuillères', categorie: 'epicerie-sucree' },
  { nom: 'Boudoirs', categorie: 'epicerie-sucree' },
  { nom: 'Spéculoos', categorie: 'epicerie-sucree' },
  { nom: 'Biscuits sablés', categorie: 'epicerie-sucree' },
  { nom: 'Crème de marrons', categorie: 'epicerie-sucree' },
  { nom: 'Chamallows', categorie: 'epicerie-sucree' },
  { nom: 'Gousse de vanille', categorie: 'epicerie-sucree' },
  { nom: 'Beurre de cacahuète', categorie: 'epicerie-sucree' },

  // Boissons
  { nom: 'Eau plate', categorie: 'boissons' },
  { nom: 'Eau gazeuse', categorie: 'boissons' },
  { nom: 'Jus d\'orange', categorie: 'boissons' },
  { nom: 'Jus de pomme', categorie: 'boissons' },
  { nom: 'Jus de pamplemousse', categorie: 'boissons' },
  { nom: 'Jus d\'ananas', categorie: 'boissons' },
  { nom: 'Jus de tomate', categorie: 'boissons' },
  { nom: 'Nectar de pêche', categorie: 'boissons' },
  { nom: 'Bière blonde', categorie: 'boissons' },
  { nom: 'Bière brune', categorie: 'boissons' },
  { nom: 'Bière blanche', categorie: 'boissons' },
  { nom: 'Vin rouge de cuisine', categorie: 'boissons' },
  { nom: 'Vin blanc de cuisine', categorie: 'boissons' },
  { nom: 'Coca-Cola', categorie: 'boissons' },
  { nom: 'Coca-Cola Zero', categorie: 'boissons' },
  { nom: 'Orangina', categorie: 'boissons' },
  { nom: 'Ice Tea', categorie: 'boissons' },
  { nom: 'Thé vert', categorie: 'boissons' },
  { nom: 'Thé noir', categorie: 'boissons' },
  { nom: 'Infusion camomille', categorie: 'boissons' },
  { nom: 'Café moulu', categorie: 'boissons' },
  { nom: 'Café en grains', categorie: 'boissons' },
  { nom: 'Café soluble', categorie: 'boissons' },
  { nom: 'Chocolat en poudre', categorie: 'boissons' },
  { nom: 'Sirop de menthe', categorie: 'boissons' },
  { nom: 'Sirop de grenadine', categorie: 'boissons' },
  { nom: 'Cidre doux', categorie: 'boissons' },
  { nom: 'Cidre brut', categorie: 'boissons' },
  { nom: 'Limonade', categorie: 'boissons' },
  { nom: 'Tonic', categorie: 'boissons' },
  { nom: 'Schweppes', categorie: 'boissons' },
  { nom: 'Champagne', categorie: 'boissons' },
  { nom: 'Crémant', categorie: 'boissons' },

  // Surgelés
  { nom: 'Frites', categorie: 'surgeles' },
  { nom: 'Poêlée de légumes du soleil', categorie: 'surgeles' },
  { nom: 'Poêlée forestière', categorie: 'surgeles' },
  { nom: 'Glace vanille', categorie: 'surgeles' },
  { nom: 'Sorbet framboise', categorie: 'surgeles' },
  { nom: 'Pizza surgelée', categorie: 'surgeles' },
  { nom: 'Pommes noisettes', categorie: 'surgeles' },
  { nom: 'Pommes duchesse', categorie: 'surgeles' },
  { nom: 'Pommes de terre rissolées', categorie: 'surgeles' },
  { nom: 'Colin d\'Alaska (pané)', categorie: 'surgeles' },
  { nom: 'Bâtonnets de colin', categorie: 'surgeles' },
  { nom: 'Poisson pané surgelé', categorie: 'surgeles' },
  { nom: 'Mélange de fruits rouges surgelés', categorie: 'surgeles' },
  { nom: 'Épinards hachés à la crème', categorie: 'surgeles' },
  { nom: 'Galettes de pommes de terre (Röstis)', categorie: 'surgeles' },
  { nom: 'Churros', categorie: 'surgeles' },
  { nom: 'Poêlée asiatique', categorie: 'surgeles' },
  { nom: 'Poêlée bretonne', categorie: 'surgeles' },
  { nom: 'Glace chocolat', categorie: 'surgeles' },
  { nom: 'Glace caramel', categorie: 'surgeles' },
  { nom: 'Sorbet citron', categorie: 'surgeles' },
  { nom: 'Glace pistache', categorie: 'surgeles' },
  { nom: 'Cônes glacés', categorie: 'surgeles' },
  { nom: 'Bûche glacée', categorie: 'surgeles' },
  { nom: 'Gyozas', categorie: 'surgeles' },
  { nom: 'Mélange de fruits de mer', categorie: 'surgeles' },
];

async function main() {
  console.log('Début du seeding des ingrédients...');
  for (const ing of INGREDIENTS) {
    await prisma.ingredient.upsert({
      where: { nom: ing.nom },
      update: { categorie: ing.categorie },
      create: { nom: ing.nom, categorie: ing.categorie },
    });
  }

  console.log(`Seeding terminé avec succès. ${INGREDIENTS.length} ingrédients insérés ou mis à jour.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error('Erreur lors du seeding:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
